Custom routing
equinor/procosys-mc-webapp pull request #127
Opened 2022-06-02 09:44 UTC by danhalvorsen

Pusing and asking for PR

2022-06-08 11:50 UTC, VRiveland reviewed
Jeg får ikke kommentert det i filen, men ser at du har lagt til package-lock.json fil. Denne ble nok generert når du brukte en npm install kommando. Vi bruker yarn i stedet, så med mindre du virkelig trenger å bruke npm så hadde det vært fint om du kunne fjernet den filen.

2022-06-08 11:50 UTC, VRiveland commented on src/routing/Http/Strategies/QueryParamsStrategy.ts
> +export class QueryParamsStrategy<T> implements IStrategy<T> {
Skulle du fortsatt beholde de ulike strategy filene? Var det bare noen som var utdaterte/unødvendige?

2022-06-08 11:50 UTC, VRiveland commented on src/routing/routing.ts
> +    const status = await statusRepository.getStatus();
Hvorfor gjør du dette her og i linje 71?

2022-06-08 11:50 UTC, VRiveland commented on src/test/strategy.test.ts
> +    it('should fail if the configuration is not valid', () => {
Denne testen tester ikke noe. Venter den på noe mer for å fullføres, eller er den bare ikke ferdigstilt?

2022-06-10 12:36 UTC, Prestholm commented on src/routing/Http/HttpResponseMessage.ts
> +    str2ab(str: string): void {
endre til "_stringToArrayBuffer()_"?

2022-06-10 12:41 UTC, Prestholm commented on src/test/hash.test.ts
> +    it('should return a different hash when paramters is swapped', () => {
*parameters

2022-06-10 12:42 UTC, Prestholm commented on src/test/httpRequestMessage.test.ts
> +    it('Test mee please', () => {
Kalle denne noe annet?

2022-06-10 12:45 UTC, Prestholm commented on src/test/types.ts
> +// >;
Cleanup?

2022-06-10 12:46 UTC, Prestholm requested changes
.

2023-09-07 10:53 UTC, closed without merging