Pbi/93611 persist post put to indexed db
equinor/procosys-mc-webapp pull request #143
Opened 2022-09-15 08:44 UTC by arildbjerkenes

Denne PR-en inneholder både persist av updates, restrukturering og oppdatering av data for new punch. 

Det ligger noe log her og der, som tas bort senere. Det blir sikkert en runde til med omstrukturering.

2022-09-22 08:11 UTC, VRiveland requested changes
I can't seem to be able to create a new punch while offline. There doesn't seem to exist a table for  saving post/put/delete in indexedDB

2022-09-22 10:34 UTC, arildbjerkenes commented on src/offline/offlineContentUpdates/handleNewPunch.ts
> +        raisedByCode: '',
Seems that in the fetch request we have RaisedByOrganizationId, but in the response we have RaisedByCode. Should we include RaisedByCode in the response from the endpoint?

2022-09-22 10:35 UTC, arildbjerkenes commented on src/offline/offlineContentUpdates/handleNewPunch.ts
> +        clearingByCode: '',
Same comment as above. We have ClearingByOrganizationId.

2022-09-22 10:38 UTC, VRiveland commented on src/offline/offlineContentUpdates/handleNewPunch.ts
> +        raisedByCode: '',
We already have the code that goes with the organzationId, see the PunchOrganization type in ApiTypes. You'll have to handle this ish the same way as matching category id to PA/PB punch type.

2022-09-22 10:40 UTC, arildbjerkenes commented on src/offline/offlineContentUpdates/handleNewPunch.ts
> +        raisedByCode: '',
Ah!

2022-09-26 09:45 UTC, VRiveland approved these changes

2022-09-26 10:14 UTC, merged